// Do not edit. This file is machine generated by the Resource DLL Wizard.

library JPG_RAR;

{$R *.RES}
{ITE} {LCID:00000804:00000804} {}
{ITE} {DFMFileType} {Forms\Unit1.dfm}
{ITE} {RCFileType} {JPG_RAR_DRC.rc}

{$R 'Forms\Unit1.dfm' Form1:TForm}
{$R 'JPG_RAR_DRC.res' 'JPG_RAR_DRC.rc'}

{$E CHS}

begin
end.